version: '3'
services:
    apache:
        build: .docker/apache
        container_name: ${CONTAINER_NAME}_apache
        ports:
          - ${APACHE_PORT}:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - ./${DIRECTORY_PROJECT}:/home/wwwroot/app
        depends_on:
          - php
        networks:
            - front-network
            - back-network

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: ${CONTAINER_NAME}_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - back-network

    php:
        build: .docker/php
        container_name: ${CONTAINER_NAME}_php
        volumes:
          - ./${DIRECTORY_PROJECT}:/home/wwwroot/app
        environment:
          - maildev_host=${CONTAINER_NAME}_maildev
        depends_on:
          - maildev
          - mysql
        networks:
            - back-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${CONTAINER_NAME}_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: ${MYSQL_PORT}
        ports:
            - ${PHPMYADMIN_PORT}:80
        links:
            - mysql
        networks:
            - back-network

    maildev:
        image: djfarrelly/maildev
        container_name: ${CONTAINER_NAME}_maildev
        ports:
          - ${MAILDEV_PORT}:80
        networks:
            - back-network

    redis:
        container_name: ${CONTAINER_NAME}_redis
        image: redis:alpine
        ports:
        - ${REDIS_PORT}:6379
        networks:
            - back-network

    centrifugo:
        container_name: ${CONTAINER_NAME}_centrifugo
        image: centrifugo/centrifugo
        command: centrifugo -c config.yml -w --port=8000  --log_level=debug --debug --insecure --address=0.0.0.0
        ports:
        - ${CENTRIFUGO_PORT}:8000
        volumes:
        - ./.docker/centrifugo/config.yml:/centrifugo/config.yml   # centrifugo -c config.json -w /opt/centrifugo/web
        networks:
            - back-network

    rabbit:
        container_name: ${CONTAINER_NAME}_rabbit
        hostname: rabbit
        image: rabbitmq:management-alpine
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        ports:
        - ${RABBIT_PORT1}:5672
        - ${RABBIT_PORT2}:15672
        networks:
            - back-network

    portainer:
        image: portainer/portainer
        container_name: ${CONTAINER_NAME}_portainer
        restart: always
        ports:
            - ${PORTAINER_PORT}:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - back-network

networks:
    front-network:
        driver: bridge
    back-network:
        driver: bridge